// <auto-generated />
using System;
using MAEVEN.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MAEVEN.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260703130108_MakeWishlistUserScoped")]
    partial class MakeWishlistUserScoped
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MAEVEN.Backend.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Discount")
                        .HasColumnType("integer");

                    b.Property<bool>("InStock")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLimited")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrending")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("OriginalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.Property<int>("ReviewsCount")
                        .HasColumnType("integer");

                    b.Property<string>("Subcategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "p1",
                            Brand = "LUXE",
                            Category = "men",
                            Description = "Impeccably tailored from premium Italian wool, this suit offers a sharp, modern silhouette perfect for any formal occasion. Features a fully lined jacket and flat-front trousers.",
                            Discount = 22,
                            InStock = true,
                            IsBestSeller = true,
                            IsLimited = false,
                            IsNew = true,
                            IsTrending = false,
                            Name = "Tailored Italian Suit",
                            OriginalPrice = 1100m,
                            Price = 850m,
                            Rating = 4.9m,
                            ReviewsCount = 124,
                            Subcategory = "Suits"
                        },
                        new
                        {
                            Id = "p2",
                            Brand = "MAISON",
                            Category = "men",
                            Description = "The quintessential white Oxford shirt. Crisp, breathable cotton and a tailored fit make this a versatile staple for both office and weekend wear.",
                            InStock = true,
                            IsBestSeller = true,
                            IsLimited = false,
                            IsNew = false,
                            IsTrending = false,
                            Name = "Classic White Oxford",
                            Price = 125m,
                            Rating = 4.7m,
                            ReviewsCount = 310,
                            Subcategory = "Shirts"
                        },
                        new
                        {
                            Id = "p3",
                            Brand = "NORD",
                            Category = "men",
                            Description = "Refined merino wool crew-neck sweater with a classic dropped shoulder. Lightweight yet warm, this versatile piece pairs with everything from denim to tailored trousers.",
                            Discount = 25,
                            InStock = true,
                            IsBestSeller = false,
                            IsLimited = false,
                            IsNew = false,
                            IsTrending = true,
                            Name = "Merino Wool Sweater",
                            OriginalPrice = 180m,
                            Price = 135m,
                            Rating = 4.8m,
                            ReviewsCount = 278,
                            Subcategory = "Knitwear"
                        },
                        new
                        {
                            Id = "p4",
                            Brand = "MAISON",
                            Category = "men",
                            Description = "Sharp, slim-cut trousers crafted from premium Italian wool blend. Features a flat front, side pockets, and a clean finish perfect for both formal and smart-casual occasions.",
                            InStock = true,
                            IsBestSeller = false,
                            IsLimited = false,
                            IsNew = false,
                            IsTrending = false,
                            Name = "Tailored Slim Trousers",
                            Price = 145m,
                            Rating = 4.6m,
                            ReviewsCount = 156,
                            Subcategory = "Trousers"
                        },
                        new
                        {
                            Id = "p5",
                            Brand = "MAISON",
                            Category = "shoes",
                            Description = "Handcrafted Oxford shoes made from smooth calfskin leather with a Goodyear-welted sole. A timeless wardrobe essential that only improves with age.",
                            Discount = 24,
                            InStock = true,
                            IsBestSeller = false,
                            IsLimited = true,
                            IsNew = false,
                            IsTrending = false,
                            Name = "Classic Oxford Shoes",
                            OriginalPrice = 375m,
                            Price = 285m,
                            Rating = 4.8m,
                            ReviewsCount = 143,
                            Subcategory = "Formal"
                        },
                        new
                        {
                            Id = "p6",
                            Brand = "NORD",
                            Category = "men",
                            Description = "A rugged, classic denim jacket with timeless appeal. Built to last and soften with every wear, featuring button-flap chest pockets and adjustable side tabs.",
                            InStock = true,
                            IsBestSeller = true,
                            IsLimited = false,
                            IsNew = false,
                            IsTrending = false,
                            Name = "Casual Denim Jacket",
                            Price = 150m,
                            Rating = 4.5m,
                            ReviewsCount = 320,
                            Subcategory = "Outerwear"
                        },
                        new
                        {
                            Id = "p7",
                            Brand = "LUXE",
                            Category = "accessories",
                            Description = "A sleek timepiece combining a precise quartz movement with a premium genuine leather strap. Features a minimalist dial that suits both casual and formal attire.",
                            InStock = true,
                            IsBestSeller = false,
                            IsLimited = false,
                            IsNew = true,
                            IsTrending = false,
                            Name = "Minimalist Leather Watch",
                            Price = 250m,
                            Rating = 4.7m,
                            ReviewsCount = 185,
                            Subcategory = "Watches"
                        },
                        new
                        {
                            Id = "p8",
                            Brand = "MAISON",
                            Category = "men",
                            Description = "Clean and versatile straight-leg chinos in a premium cotton twill. The perfect balance of comfort and refinement for any occasion.",
                            Discount = 27,
                            InStock = true,
                            IsBestSeller = false,
                            IsLimited = false,
                            IsNew = false,
                            IsTrending = true,
                            Name = "Straight Leg Chinos",
                            OriginalPrice = 130m,
                            Price = 95m,
                            Rating = 4.5m,
                            ReviewsCount = 267,
                            Subcategory = "Trousers"
                        });
                });

            modelBuilder.Entity("MAEVEN.Backend.Models.ProductColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductColors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = "p1",
                            Value = "#1a1a1a"
                        },
                        new
                        {
                            Id = 2,
                            ProductId = "p1",
                            Value = "#2c3e50"
                        },
                        new
                        {
                            Id = 3,
                            ProductId = "p2",
                            Value = "#ffffff"
                        },
                        new
                        {
                            Id = 4,
                            ProductId = "p2",
                            Value = "#f5f5f0"
                        },
                        new
                        {
                            Id = 5,
                            ProductId = "p3",
                            Value = "#4a4a4a"
                        },
                        new
                        {
                            Id = 6,
                            ProductId = "p3",
                            Value = "#1a1a1a"
                        },
                        new
                        {
                            Id = 7,
                            ProductId = "p3",
                            Value = "#d4c5a9"
                        },
                        new
                        {
                            Id = 8,
                            ProductId = "p3",
                            Value = "#8b4513"
                        },
                        new
                        {
                            Id = 9,
                            ProductId = "p4",
                            Value = "#1a1a1a"
                        },
                        new
                        {
                            Id = 10,
                            ProductId = "p4",
                            Value = "#4a4a4a"
                        },
                        new
                        {
                            Id = 11,
                            ProductId = "p4",
                            Value = "#c4a882"
                        },
                        new
                        {
                            Id = 12,
                            ProductId = "p4",
                            Value = "#2c3e50"
                        },
                        new
                        {
                            Id = 13,
                            ProductId = "p5",
                            Value = "#1a1a1a"
                        },
                        new
                        {
                            Id = 14,
                            ProductId = "p5",
                            Value = "#8b4513"
                        },
                        new
                        {
                            Id = 15,
                            ProductId = "p5",
                            Value = "#c4a882"
                        },
                        new
                        {
                            Id = 16,
                            ProductId = "p6",
                            Value = "#2c3e50"
                        },
                        new
                        {
                            Id = 17,
                            ProductId = "p6",
                            Value = "#1a1a1a"
                        },
                        new
                        {
                            Id = 18,
                            ProductId = "p6",
                            Value = "#d4c5a9"
                        },
                        new
                        {
                            Id = 19,
                            ProductId = "p7",
                            Value = "#1a1a1a"
                        },
                        new
                        {
                            Id = 20,
                            ProductId = "p7",
                            Value = "#8b4513"
                        },
                        new
                        {
                            Id = 21,
                            ProductId = "p8",
                            Value = "#c4a882"
                        },
                        new
                        {
                            Id = 22,
                            ProductId = "p8",
                            Value = "#1a1a1a"
                        },
                        new
                        {
                            Id = 23,
                            ProductId = "p8",
                            Value = "#4a4a4a"
                        },
                        new
                        {
                            Id = 24,
                            ProductId = "p8",
                            Value = "#2c3e50"
                        });
                });

            modelBuilder.Entity("MAEVEN.Backend.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = "p1",
                            SortOrder = 1,
                            Url = "https://images.unsplash.com/photo-1618886614638-80e3c103d31a?w=800&q=80"
                        },
                        new
                        {
                            Id = 2,
                            ProductId = "p1",
                            SortOrder = 2,
                            Url = "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&q=80"
                        },
                        new
                        {
                            Id = 3,
                            ProductId = "p2",
                            SortOrder = 1,
                            Url = "https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800&q=80"
                        },
                        new
                        {
                            Id = 4,
                            ProductId = "p2",
                            SortOrder = 2,
                            Url = "https://images.unsplash.com/photo-1596755094514-f87e32f85e2c?w=800&q=80"
                        },
                        new
                        {
                            Id = 5,
                            ProductId = "p3",
                            SortOrder = 1,
                            Url = "https://images.unsplash.com/photo-1574427797991-b086946fa9e7?w=800&q=80"
                        },
                        new
                        {
                            Id = 6,
                            ProductId = "p3",
                            SortOrder = 2,
                            Url = "https://images.unsplash.com/photo-1554925051-f668ed70d520?w=800&q=80"
                        },
                        new
                        {
                            Id = 7,
                            ProductId = "p4",
                            SortOrder = 1,
                            Url = "https://images.unsplash.com/photo-1582225905616-c3adc77ada6b?w=800&q=80"
                        },
                        new
                        {
                            Id = 8,
                            ProductId = "p4",
                            SortOrder = 2,
                            Url = "https://images.unsplash.com/photo-1523585298601-d46ae038d7d3?w=800&q=80"
                        },
                        new
                        {
                            Id = 9,
                            ProductId = "p5",
                            SortOrder = 1,
                            Url = "https://images.unsplash.com/photo-1668069226492-508742b03147?w=800&q=80"
                        },
                        new
                        {
                            Id = 10,
                            ProductId = "p5",
                            SortOrder = 2,
                            Url = "https://images.unsplash.com/photo-1614252339460-e143130d2aa2?w=800&q=80"
                        },
                        new
                        {
                            Id = 11,
                            ProductId = "p6",
                            SortOrder = 1,
                            Url = "https://images.unsplash.com/photo-1495105787522-5334e3ffa0ebd?w=800&q=80"
                        },
                        new
                        {
                            Id = 12,
                            ProductId = "p6",
                            SortOrder = 2,
                            Url = "https://images.unsplash.com/photo-1543076447-215ad9ba6923?w=800&q=80"
                        },
                        new
                        {
                            Id = 13,
                            ProductId = "p7",
                            SortOrder = 1,
                            Url = "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?w=800&q=80"
                        },
                        new
                        {
                            Id = 14,
                            ProductId = "p7",
                            SortOrder = 2,
                            Url = "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&q=80"
                        },
                        new
                        {
                            Id = 15,
                            ProductId = "p8",
                            SortOrder = 1,
                            Url = "https://images.unsplash.com/photo-1617114919297-3c8ddb01f599?w=800&q=80"
                        },
                        new
                        {
                            Id = 16,
                            ProductId = "p8",
                            SortOrder = 2,
                            Url = "https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?w=800&q=80"
                        });
                });

            modelBuilder.Entity("MAEVEN.Backend.Models.ProductSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSizes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = "p1",
                            Value = "38R"
                        },
                        new
                        {
                            Id = 2,
                            ProductId = "p1",
                            Value = "40R"
                        },
                        new
                        {
                            Id = 3,
                            ProductId = "p1",
                            Value = "42R"
                        },
                        new
                        {
                            Id = 4,
                            ProductId = "p1",
                            Value = "44R"
                        },
                        new
                        {
                            Id = 5,
                            ProductId = "p2",
                            Value = "S"
                        },
                        new
                        {
                            Id = 6,
                            ProductId = "p2",
                            Value = "M"
                        },
                        new
                        {
                            Id = 7,
                            ProductId = "p2",
                            Value = "L"
                        },
                        new
                        {
                            Id = 8,
                            ProductId = "p2",
                            Value = "XL"
                        },
                        new
                        {
                            Id = 9,
                            ProductId = "p2",
                            Value = "XXL"
                        },
                        new
                        {
                            Id = 10,
                            ProductId = "p3",
                            Value = "S"
                        },
                        new
                        {
                            Id = 11,
                            ProductId = "p3",
                            Value = "M"
                        },
                        new
                        {
                            Id = 12,
                            ProductId = "p3",
                            Value = "L"
                        },
                        new
                        {
                            Id = 13,
                            ProductId = "p3",
                            Value = "XL"
                        },
                        new
                        {
                            Id = 14,
                            ProductId = "p3",
                            Value = "XXL"
                        },
                        new
                        {
                            Id = 15,
                            ProductId = "p4",
                            Value = "28"
                        },
                        new
                        {
                            Id = 16,
                            ProductId = "p4",
                            Value = "30"
                        },
                        new
                        {
                            Id = 17,
                            ProductId = "p4",
                            Value = "32"
                        },
                        new
                        {
                            Id = 18,
                            ProductId = "p4",
                            Value = "34"
                        },
                        new
                        {
                            Id = 19,
                            ProductId = "p4",
                            Value = "36"
                        },
                        new
                        {
                            Id = 20,
                            ProductId = "p4",
                            Value = "38"
                        },
                        new
                        {
                            Id = 21,
                            ProductId = "p5",
                            Value = "39"
                        },
                        new
                        {
                            Id = 22,
                            ProductId = "p5",
                            Value = "40"
                        },
                        new
                        {
                            Id = 23,
                            ProductId = "p5",
                            Value = "41"
                        },
                        new
                        {
                            Id = 24,
                            ProductId = "p5",
                            Value = "42"
                        },
                        new
                        {
                            Id = 25,
                            ProductId = "p5",
                            Value = "43"
                        },
                        new
                        {
                            Id = 26,
                            ProductId = "p5",
                            Value = "44"
                        },
                        new
                        {
                            Id = 27,
                            ProductId = "p5",
                            Value = "45"
                        },
                        new
                        {
                            Id = 28,
                            ProductId = "p6",
                            Value = "S"
                        },
                        new
                        {
                            Id = 29,
                            ProductId = "p6",
                            Value = "M"
                        },
                        new
                        {
                            Id = 30,
                            ProductId = "p6",
                            Value = "L"
                        },
                        new
                        {
                            Id = 31,
                            ProductId = "p6",
                            Value = "XL"
                        },
                        new
                        {
                            Id = 32,
                            ProductId = "p7",
                            Value = "One Size"
                        },
                        new
                        {
                            Id = 33,
                            ProductId = "p8",
                            Value = "28"
                        },
                        new
                        {
                            Id = 34,
                            ProductId = "p8",
                            Value = "30"
                        },
                        new
                        {
                            Id = 35,
                            ProductId = "p8",
                            Value = "32"
                        },
                        new
                        {
                            Id = 36,
                            ProductId = "p8",
                            Value = "34"
                        },
                        new
                        {
                            Id = 37,
                            ProductId = "p8",
                            Value = "36"
                        },
                        new
                        {
                            Id = 38,
                            ProductId = "p8",
                            Value = "38"
                        },
                        new
                        {
                            Id = 39,
                            ProductId = "p8",
                            Value = "40"
                        });
                });

            modelBuilder.Entity("MAEVEN.Backend.Models.ProductSpecification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSpecifications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Material",
                            ProductId = "p1",
                            Value = "100% Wool"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Care",
                            ProductId = "p1",
                            Value = "Dry Clean Only"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fit",
                            ProductId = "p1",
                            Value = "Slim Fit"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Origin",
                            ProductId = "p1",
                            Value = "Italy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Material",
                            ProductId = "p2",
                            Value = "100% Cotton"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Care",
                            ProductId = "p2",
                            Value = "Machine Wash"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Fit",
                            ProductId = "p2",
                            Value = "Tailored"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Collar",
                            ProductId = "p2",
                            Value = "Button-down"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Material",
                            ProductId = "p3",
                            Value = "100% Extra-Fine Merino Wool"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Gauge",
                            ProductId = "p3",
                            Value = "12-Gauge Knit"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Care",
                            ProductId = "p3",
                            Value = "Machine Wash Gentle"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Fit",
                            ProductId = "p3",
                            Value = "Regular"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Material",
                            ProductId = "p4",
                            Value = "70% Wool, 30% Polyester"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Care",
                            ProductId = "p4",
                            Value = "Dry Clean"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Fit",
                            ProductId = "p4",
                            Value = "Slim Straight"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Rise",
                            ProductId = "p4",
                            Value = "Mid Rise"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Material",
                            ProductId = "p5",
                            Value = "Calfskin Leather Upper"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Sole",
                            ProductId = "p5",
                            Value = "Leather Goodyear Welt"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Lining",
                            ProductId = "p5",
                            Value = "Leather"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Origin",
                            ProductId = "p5",
                            Value = "Italy"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Material",
                            ProductId = "p6",
                            Value = "100% Cotton Denim"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Fit",
                            ProductId = "p6",
                            Value = "Regular"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Care",
                            ProductId = "p6",
                            Value = "Machine Wash Cold"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Origin",
                            ProductId = "p6",
                            Value = "Japan"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Material",
                            ProductId = "p7",
                            Value = "Stainless Steel Case, Leather Strap"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Movement",
                            ProductId = "p7",
                            Value = "Quartz"
                        },
                        new
                        {
                            Id = 27,
                            Name = "WaterResistance",
                            ProductId = "p7",
                            Value = "5 ATM"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Face",
                            ProductId = "p7",
                            Value = "40mm"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Material",
                            ProductId = "p8",
                            Value = "98% Cotton, 2% Elastane"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Rise",
                            ProductId = "p8",
                            Value = "Regular"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Fit",
                            ProductId = "p8",
                            Value = "Straight"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Care",
                            ProductId = "p8",
                            Value = "Machine Wash"
                        });
                });

            modelBuilder.Entity("MAEVEN.Backend.Models.ProductTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductTags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = "p1",
                            Value = "suit"
                        },
                        new
                        {
                            Id = 2,
                            ProductId = "p1",
                            Value = "formal"
                        },
                        new
                        {
                            Id = 3,
                            ProductId = "p1",
                            Value = "wool"
                        },
                        new
                        {
                            Id = 4,
                            ProductId = "p1",
                            Value = "italian"
                        },
                        new
                        {
                            Id = 5,
                            ProductId = "p2",
                            Value = "shirt"
                        },
                        new
                        {
                            Id = 6,
                            ProductId = "p2",
                            Value = "oxford"
                        },
                        new
                        {
                            Id = 7,
                            ProductId = "p2",
                            Value = "white"
                        },
                        new
                        {
                            Id = 8,
                            ProductId = "p2",
                            Value = "staple"
                        },
                        new
                        {
                            Id = 9,
                            ProductId = "p2",
                            Value = "cotton"
                        },
                        new
                        {
                            Id = 10,
                            ProductId = "p3",
                            Value = "merino"
                        },
                        new
                        {
                            Id = 11,
                            ProductId = "p3",
                            Value = "wool"
                        },
                        new
                        {
                            Id = 12,
                            ProductId = "p3",
                            Value = "sweater"
                        },
                        new
                        {
                            Id = 13,
                            ProductId = "p3",
                            Value = "knitwear"
                        },
                        new
                        {
                            Id = 14,
                            ProductId = "p3",
                            Value = "versatile"
                        },
                        new
                        {
                            Id = 15,
                            ProductId = "p4",
                            Value = "trousers"
                        },
                        new
                        {
                            Id = 16,
                            ProductId = "p4",
                            Value = "slim"
                        },
                        new
                        {
                            Id = 17,
                            ProductId = "p4",
                            Value = "tailored"
                        },
                        new
                        {
                            Id = 18,
                            ProductId = "p4",
                            Value = "formal"
                        },
                        new
                        {
                            Id = 19,
                            ProductId = "p5",
                            Value = "oxford"
                        },
                        new
                        {
                            Id = 20,
                            ProductId = "p5",
                            Value = "shoes"
                        },
                        new
                        {
                            Id = 21,
                            ProductId = "p5",
                            Value = "leather"
                        },
                        new
                        {
                            Id = 22,
                            ProductId = "p5",
                            Value = "formal"
                        },
                        new
                        {
                            Id = 23,
                            ProductId = "p5",
                            Value = "italian"
                        },
                        new
                        {
                            Id = 24,
                            ProductId = "p6",
                            Value = "denim"
                        },
                        new
                        {
                            Id = 25,
                            ProductId = "p6",
                            Value = "jacket"
                        },
                        new
                        {
                            Id = 26,
                            ProductId = "p6",
                            Value = "casual"
                        },
                        new
                        {
                            Id = 27,
                            ProductId = "p6",
                            Value = "outerwear"
                        },
                        new
                        {
                            Id = 28,
                            ProductId = "p7",
                            Value = "watch"
                        },
                        new
                        {
                            Id = 29,
                            ProductId = "p7",
                            Value = "leather"
                        },
                        new
                        {
                            Id = 30,
                            ProductId = "p7",
                            Value = "accessory"
                        },
                        new
                        {
                            Id = 31,
                            ProductId = "p7",
                            Value = "minimalist"
                        },
                        new
                        {
                            Id = 32,
                            ProductId = "p8",
                            Value = "chinos"
                        },
                        new
                        {
                            Id = 33,
                            ProductId = "p8",
                            Value = "casual"
                        },
                        new
                        {
                            Id = 34,
                            ProductId = "p8",
                            Value = "versatile"
                        },
                        new
                        {
                            Id = 35,
                            ProductId = "p8",
                            Value = "cotton"
                        });
                });

            modelBuilder.Entity("MAEVEN.Backend.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Helpful")
                        .HasColumnType("integer");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=60&q=80",
                            Comment = "The tailoring on this suit is exceptional. It fits perfectly right out of the box and the material feels incredibly premium. Wore it to a wedding and felt great.",
                            Date = new DateOnly(2026, 5, 15),
                            Helpful = 24,
                            ProductId = "p1",
                            Rating = 5,
                            User = "James W."
                        },
                        new
                        {
                            Id = 2,
                            AvatarUrl = "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=60&q=80",
                            Comment = "Worth the investment. The silhouette is very modern without being too skinny.",
                            Date = new DateOnly(2026, 5, 2),
                            Helpful = 18,
                            ProductId = "p1",
                            Rating = 5,
                            User = "Michael T."
                        },
                        new
                        {
                            Id = 3,
                            AvatarUrl = "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=60&q=80",
                            Comment = "Great sweater, very soft. I had to size up to get the relaxed fit I wanted, but the quality is top notch.",
                            Date = new DateOnly(2026, 4, 28),
                            Helpful = 31,
                            ProductId = "p3",
                            Rating = 4,
                            User = "David L."
                        });
                });

            modelBuilder.Entity("MAEVEN.Backend.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "u1",
                            Avatar = "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=80&q=80",
                            CreatedAt = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@maeven.com",
                            Name = "Admin User",
                            PasswordHash = "$2a$11$cdkcUEXJmsyju9ECU6rAVeuB0XD2ve7OndUrvpgSfXZuqVAYCixUq",
                            Role = "admin",
                            Tier = "Platinum"
                        },
                        new
                        {
                            Id = "u2",
                            Avatar = "https://images.unsplash.com/photo-1494790108755-2616b332e234?w=80&q=80",
                            CreatedAt = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alex.rivera@email.com",
                            Name = "Alexandra Rivera",
                            PasswordHash = "$2a$11$0RWlqyKf2X.wK01fMRWeDO7xugtg8L4qq7jUhRI4tbcox.7AGFv02",
                            Role = "user",
                            Tier = "Gold"
                        });
                });

            modelBuilder.Entity("MAEVEN.Backend.Models.WishlistItem", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProductId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("WishlistItems", (string)null);
                });

            modelBuilder.Entity("MAEVEN.Backend.Models.ProductColor", b =>
                {
                    b.HasOne("MAEVEN.Backend.Models.Product", "Product")
                        .WithMany("Colors")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MAEVEN.Backend.Models.ProductImage", b =>
                {
                    b.HasOne("MAEVEN.Backend.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MAEVEN.Backend.Models.ProductSize", b =>
                {
                    b.HasOne("MAEVEN.Backend.Models.Product", "Product")
                        .WithMany("Sizes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MAEVEN.Backend.Models.ProductSpecification", b =>
                {
                    b.HasOne("MAEVEN.Backend.Models.Product", "Product")
                        .WithMany("Specifications")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MAEVEN.Backend.Models.ProductTag", b =>
                {
                    b.HasOne("MAEVEN.Backend.Models.Product", "Product")
                        .WithMany("Tags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MAEVEN.Backend.Models.Review", b =>
                {
                    b.HasOne("MAEVEN.Backend.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MAEVEN.Backend.Models.WishlistItem", b =>
                {
                    b.HasOne("MAEVEN.Backend.Models.Product", "Product")
                        .WithMany("WishlistItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAEVEN.Backend.Models.User", "User")
                        .WithMany("WishlistItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MAEVEN.Backend.Models.Product", b =>
                {
                    b.Navigation("Colors");

                    b.Navigation("Images");

                    b.Navigation("Reviews");

                    b.Navigation("Sizes");

                    b.Navigation("Specifications");

                    b.Navigation("Tags");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("MAEVEN.Backend.Models.User", b =>
                {
                    b.Navigation("WishlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
